# Generated by Django 4.2 on 2025-01-22 17:23

import client.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییرات')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('account_number', models.CharField(max_length=100, verbose_name='شماره حساب')),
                ('kind', models.CharField(choices=[('current', 'حساب جاری'), ('short', 'حساب کوتاه مدت'), ('LOAN', 'حساب قرض\u200cالحسنه')], default='current', max_length=100, verbose_name='نوع حساب')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ایجاد')),
                ('user_modified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_modified', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ویرایش')),
            ],
            options={
                'verbose_name': 'حساب بانک',
                'verbose_name_plural': 'حساب بانک\u200cها',
            },
        ),
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییرات')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('sid', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد معین')),
                ('kind', models.CharField(choices=[('real', 'حقیقی'), ('legal', 'حقوقی')], default='real', max_length=50, verbose_name='نوع مشارکت کننده')),
                ('brand', models.CharField(max_length=100, verbose_name='نام تجاری')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام شرکت')),
                ('ceoname', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مدیرعامل')),
                ('ncode', models.CharField(blank=True, max_length=11, null=True, verbose_name='شناسه ملی')),
                ('mobile', models.CharField(max_length=11, verbose_name='موبایل')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفن')),
                ('fax', models.CharField(blank=True, max_length=11, null=True, verbose_name='فکس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('postalcode', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ایجاد')),
                ('user_modified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_modified', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ویرایش')),
            ],
            options={
                'verbose_name': 'مشارکت کننده',
                'verbose_name_plural': 'مشارکت کنندگان',
            },
        ),
        migrations.CreateModel(
            name='DepositModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییرات')),
                ('state', models.CharField(choices=[('deposit', 'بیعانه'), ('return', 'عودت'), ('payment', 'اضافه به حساب')], default='deposit', max_length=50, verbose_name='وضعیت')),
                ('invoice_number', models.CharField(max_length=100, unique=True, verbose_name='شماره سند')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('customer', models.ForeignKey(max_length='مشارکت کننده', on_delete=django.db.models.deletion.PROTECT, to='client.customermodel')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ایجاد')),
                ('user_modified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_modified', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ویرایش')),
            ],
            options={
                'verbose_name': 'بیعانه',
                'verbose_name_plural': 'بیعانه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ExhibitionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییرات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sid', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد معین')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان نمایشگاه')),
                ('price', models.CharField(max_length=20, verbose_name='قیمت')),
                ('value_added', models.CharField(max_length=10, verbose_name='ارزش افزوده')),
                ('min_area', models.CharField(max_length=100, verbose_name='حداقل متراژ(مترمربع)')),
                ('date', models.DateField(blank=True, null=True, verbose_name='تاریخ برگزاری')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ایجاد')),
                ('user_modified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_modified', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ویرایش')),
            ],
            options={
                'verbose_name': 'نمایشگاه',
                'verbose_name_plural': 'نمایشگاه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='InvoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییرات')),
                ('state', models.CharField(choices=[('paid', 'پرداخت شده'), ('unpaid', 'پرداخت نشده')], default='unpaid', max_length=50, verbose_name='وضعیت')),
                ('amount', models.CharField(max_length=20, verbose_name='مبلغ')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.customermodel', verbose_name='مشارکت کننده')),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.exhibitionmodel', verbose_name='نمایشگاه')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ایجاد')),
                ('user_modified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_modified', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ویرایش')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
            },
        ),
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییرات')),
                ('state', models.CharField(choices=[('check', 'چک بانکی'), ('cashe', 'نقدی'), ('pos', 'پوز بانکی')], default='pos', max_length=50, verbose_name='وضعیت')),
                ('amount', models.IntegerField(default=1000, verbose_name='مبلغ')),
                ('cardnumber', models.CharField(blank=True, max_length=32, null=True, verbose_name='شماره کارت/چک')),
                ('issuerbank', models.CharField(blank=True, max_length=150, null=True, verbose_name='بانک صادرکننده')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='مشخصات صاحب چک')),
                ('rrn', models.CharField(blank=True, max_length=150, null=True, verbose_name='شماره سند بانکی')),
                ('tracenumber', models.CharField(blank=True, max_length=150, null=True, verbose_name='شماره پیگیری')),
                ('digitalreceipt', models.CharField(blank=True, max_length=150, null=True, verbose_name='رسید دیجیتال')),
                ('respcode', models.IntegerField(blank=True, default=0, null=True, verbose_name='کد نتیجه تراکنش')),
                ('respmsg', models.CharField(blank=True, max_length=150, null=True, verbose_name='متن نتیجه تراکنش')),
                ('payload', models.CharField(blank=True, max_length=150, null=True, verbose_name='توضیحات')),
                ('datepaid', models.CharField(blank=True, max_length=50, null=True, verbose_name='تاریخ و زمان تراکنش')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.bankmodel', verbose_name='حساب بانکی')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.invoicemodel', verbose_name='فاکتور')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ایجاد')),
                ('user_modified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_modified', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ویرایش')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییرات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('booth_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره غرفه')),
                ('price', models.CharField(max_length=20, verbose_name='مبلغ')),
                ('area', models.CharField(default='0', max_length=9, verbose_name='متراژ(مترمربع)')),
                ('value_added', models.CharField(default='0', max_length=10, verbose_name='ارزش افزوده')),
                ('discount', models.CharField(blank=True, max_length=20, null=True, verbose_name='تخفیف(درصد)')),
                ('total_price', models.CharField(max_length=20, verbose_name='مبلغ نهایی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.invoicemodel', verbose_name='فاکتور')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ایجاد')),
                ('user_modified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_modified', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ویرایش')),
            ],
            options={
                'verbose_name': 'اقلام فاکتور',
                'verbose_name_plural': 'اقلام فاکتورها',
            },
        ),
        migrations.CreateModel(
            name='DocumentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییرات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('state', models.CharField(choices=[('wait', 'در انتظار بررسی'), ('accept', 'قبول شده'), ('deny', 'رد شده')], default='wait', max_length=50, verbose_name='وضعیت')),
                ('file', models.FileField(upload_to=client.models.documents_directory_path, verbose_name='مدرک')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.customermodel', verbose_name='مشارکت کننده')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ایجاد')),
                ('user_modified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_modified', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ویرایش')),
            ],
            options={
                'verbose_name': 'مدرک',
                'verbose_name_plural': 'مدارک',
            },
        ),
        migrations.CreateModel(
            name='DepositPaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییرات')),
                ('date', models.DateField(verbose_name='تاریخ رسید')),
                ('tracenumber', models.CharField(blank=True, max_length=150, null=True, verbose_name='شماره پیگیری')),
                ('amount', models.CharField(default='0', max_length=12, verbose_name='مبلغ')),
                ('deposit', models.ForeignKey(max_length='بیعانه', on_delete=django.db.models.deletion.PROTECT, to='client.depositmodel')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ایجاد')),
                ('user_modified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_modified', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ویرایش')),
            ],
            options={
                'verbose_name': 'رسید بیعانه',
                'verbose_name_plural': 'رسید بیعانه\u200cها',
            },
        ),
        migrations.AddConstraint(
            model_name='paymentmodel',
            constraint=models.UniqueConstraint(fields=('digitalreceipt',), name='specdr'),
        ),
        migrations.AddConstraint(
            model_name='invoicemodel',
            constraint=models.UniqueConstraint(fields=('exhibition', 'customer'), name='excus'),
        ),
        migrations.AddConstraint(
            model_name='customermodel',
            constraint=models.UniqueConstraint(fields=('brand', 'user'), name='branduser'),
        ),
        migrations.AddConstraint(
            model_name='customermodel',
            constraint=models.UniqueConstraint(fields=('brand', 'company'), name='brandcompany'),
        ),
        migrations.AddConstraint(
            model_name='customermodel',
            constraint=models.UniqueConstraint(fields=('sid',), name='specid'),
        ),
    ]
