# Generated by Django 4.2 on 2025-01-22 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodel',
            name='mobile',
        ),
    ]
