# Generated by Django 4.2 on 2025-01-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_customermodel_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='first_name',
            field=models.CharField(default='ali', max_length=100, verbose_name='نام'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customermodel',
            name='last_name',
            field=models.CharField(default='hasani', max_length=100, verbose_name='نام خانوادگی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customermodel',
            name='mobile',
            field=models.CharField(default='09379896361', max_length=11, verbose_name='موبایل'),
            preserve_default=False,
        ),
    ]
