# Generated by Django 4.2 on 2025-05-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_rename_valetmodel_walletmodel_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoicemodel',
            name='customerex',
        ),
        migrations.AddConstraint(
            model_name='invoicemodel',
            constraint=models.UniqueConstraint(fields=('customer', 'exhibition', 'booth_number'), name='customer_exhibition_booth'),
        ),
    ]
