# Generated by Django 4.2 on 2025-01-26 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0003_customermodel_code_customermodel_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییرات')),
                ('cash', models.CharField(max_length=15, verbose_name='موجودی(ریال)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ایجاد')),
                ('user_modified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_modified', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ویرایش')),
            ],
            options={
                'verbose_name': 'کیف پول',
                'verbose_name_plural': 'کیف\u200cهای پول',
            },
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='area',
            field=models.CharField(default='0', max_length=9, verbose_name='متراژ(مترمربع)'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='booth_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره غرفه'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='discount',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='تخفیف(درصد)'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='price',
            field=models.CharField(default='0', max_length=20, verbose_name='مبلغ'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='value_added',
            field=models.CharField(default='0', max_length=10, verbose_name='ارزش افزوده(درصد)'),
        ),
        migrations.AlterField(
            model_name='bankmodel',
            name='kind',
            field=models.CharField(choices=[('current', 'حساب جاری'), ('short', 'حساب کوتاه مدت'), ('loan', 'حساب قرض\u200cالحسنه')], default='current', max_length=100, verbose_name='نوع حساب'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='amount',
            field=models.CharField(max_length=20, verbose_name='مبلغ نهایی'),
        ),
        migrations.DeleteModel(
            name='InvoiceItemModel',
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='valet',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='client.valetmodel', verbose_name='کیف پول کاربر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='valet',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='client.valetmodel', verbose_name='کیف پول کاربر'),
            preserve_default=False,
        ),
    ]
