# Generated by Django 4.2 on 2025-01-27 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_valetmodel_remove_paymentmodel_invoice_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoicemodel',
            name='excus',
        ),
        migrations.RemoveField(
            model_name='depositmodel',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='invoicemodel',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='valetmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='depositmodel',
            name='valet',
            field=models.ForeignKey(default=1, max_length='کیف پول', on_delete=django.db.models.deletion.PROTECT, to='client.valetmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valetmodel',
            name='customer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='client.customermodel', verbose_name='مشارکت کننده'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='amount',
            field=models.CharField(default='0', max_length=20, verbose_name='مبلغ نهایی'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='discount',
            field=models.CharField(default='0', max_length=3, verbose_name='تخفیف(درصد)'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='valet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.valetmodel', verbose_name='کیف پول'),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='valet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.valetmodel', verbose_name='کیف پول'),
        ),
    ]
