# Generated by Django 4.2 on 2025-05-18 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_remove_documentsmodel_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentsmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='documentsmodel',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.customermodel', verbose_name='کاربر'),
        ),
    ]
