# Generated by Django 4.2 on 2025-05-18 20:03

import client.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0005_remove_documentsmodel_user_documentsmodel_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییرات')),
                ('state', models.CharField(choices=[('accept', 'قبول شده'), ('deny', 'رد شده'), ('wait', 'انتظار')], default='wait', max_length=50, verbose_name='وضعیت')),
                ('rules', models.BooleanField(verbose_name='قوانین')),
                ('description', models.TextField(verbose_name='توضیحات و محصولات')),
                ('message', models.TextField(verbose_name='پیام')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.customermodel', verbose_name='مشارکت کننده')),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.exhibitionmodel', verbose_name='عنوان نمایشگاه')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ایجاد')),
                ('user_modified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_modified', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ویرایش')),
            ],
            options={
                'verbose_name': 'درخواست',
                'verbose_name_plural': 'درخواست\u200cها',
            },
        ),
        migrations.CreateModel(
            name='RequestDocumentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییرات')),
                ('file', models.FileField(upload_to=client.models.request_documents_directory_path, verbose_name='مدارک')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.requestmodel', verbose_name='درخواست')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ایجاد')),
                ('user_modified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_modified', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ویرایش')),
            ],
            options={
                'verbose_name': 'مدرک درخواست',
                'verbose_name_plural': 'مدارک درخواست\u200cها',
            },
        ),
        migrations.AddConstraint(
            model_name='requestmodel',
            constraint=models.UniqueConstraint(fields=('exhibition', 'customer'), name='exhcus'),
        ),
    ]
