# Generated by Django 4.2 on 2025-05-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_requestmodel_requestdocumentsmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='پیام'),
        ),
    ]
