# Generated by Django 4.2 on 2025-01-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_alter_paymentmodel_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='state',
            field=models.CharField(choices=[('check', 'چک بانکی'), ('cash', 'نقدی'), ('pos', 'پوز بانکی'), ('ipg', 'درگاه اینترنتی')], default='pos', max_length=50, verbose_name='وضعیت'),
        ),
    ]
