# Generated by Django 4.2 on 2025-02-03 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_alter_paymentmodel_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositmodel',
            name='valet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.valetmodel', verbose_name='کیف پول'),
        ),
    ]
