# Generated by Django 4.2 on 2025-02-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_alter_depositmodel_valet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositpaymentmodel',
            name='date',
            field=models.CharField(max_length=10, verbose_name='تاریخ رسید'),
        ),
    ]
