# Generated by Django 4.2 on 2025-02-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_alter_depositpaymentmodel_date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invoicemodel',
            constraint=models.UniqueConstraint(fields=('valet', 'exhibition'), name='valetex'),
        ),
    ]
