# Generated by Django 4.2 on 2025-02-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_invoicemodel_valetex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='sid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد تفصیلی'),
        ),
    ]
